name: covanalyser
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python=3.6
  - biopython
  - pandas
  - mafft
  - tracy
  - ivar
  - samtools
  - htslib
  - bcftools
  - minimap2
  - bowtie2
